default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password: password
  pool: 5

development:
  <<: *default
  database: my_portfolio_development

test:
  <<: *default
  database: my_portfolio_test

production:
  <<: *default
  database: my_portfolio_production
  username: my_portfolio
  password: <%= ENV['MY_PORTFOLIO_DATABASE_PASSWORD'] %>
